name: Build and Deploy ScrapeWise to Railway

on:
  workflow_dispatch:  # Manual trigger only
  # Disabled automatic deployment - now using Azure workflow
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish -c Release -o ./publish
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-artifact
        path: ./publish

  deploy-railway:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: app-artifact
        path: ./publish
    
    - name: Deploy to Railway
      uses: railway/deploy@v1
      with:
        service: scrapewise
        token: ${{ secrets.RAILWAY_TOKEN }} 